# This is a basic workflow to help you get started with Actions
# name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: "us-east-1" # Change to reflect your Region

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Change to your required Node.js version

      - name: Install dependencies
        run: sudo npm install

      - name: Build the project
        run: npm run build

      - name: Collect build artifacts
        run: |
          mkdir build
          cp -r dist/* build/ # Change to your build output directory
          cp -r front/public/* build/ # Change to your build output directory

      - name: Archive build files
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/ # Change to your build output directory

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/ # Change to your build output directory

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::443370698448:role/GitHubAction-AssumeRoleWithAction # Change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name "TrustworthyPackageRegistry" \
          --deployment-group-name "TPRDeploymentGroup" \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
