# name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: "us-east-1" # Change to reflect your Region

permissions:
  id-token: write
  contents: read

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Adjust as needed

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Collect build artifacts
        run: |
          mkdir build
          cp -r dist/* build/  # Adjust to your build output directory if different
          cp -r front/public/* build/  # Adjust as needed

      - name: Archive build files
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::443370698448:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity

      - name: Deploy to AWS CodeDeploy
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name "TrustworthyPackageRegistry" \
          --deployment-group-name "TPRDeploymentGroup" \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
