name: Run testing pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Run testing script
      env:
          GITHUB_TOKEN: ${{ secrets.CI_API_TOKEN }}
      run: 
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "GITHUB_TOKEN is not set"
          else
            echo "MY_VARIABLE is set to:" $GITHUB_TOKEN
          fi
          npm run test
